### PR TITLE
Add Group By Pipe

### PR DESCRIPTION
**Pull request by paulussup**
Didn't see anything like this. I find it is useful.

### CODE REVIEW

**Comment by danrevah** [comment]
Looks good .. Thanks!
I will add a documentation for it.

**Comment by danrevah** [comment]
Added  to version #v0.5.2 with small changes in behaviour, it will now return an object that it's property will be the grouped by property.

Take a look at the readme file for more documentation, if you would like to it in an ngFor you could add an additional `keys` pipe to loop over it, since Angular2 doesn't support  loop over objects.

**Comment by paulussup** [comment]
Looks good. Would it make sense to have another pipe like lodash’s toPairs? 

https://github.com/lodash/lodash/blob/4.17.2/lodash.js#L1011 <https://github.com/lodash/lodash/blob/4.17.2/lodash.js#L1011>

**Comment by danrevah** [comment]
Might be a good idea yeah. 
I'll try to find a time for it.

**Comment by danrevah** [comment]
@paulussup Added some object pipes: https://github.com/danrevah/ng2-pipes#object

**Pull request merged**
